fields:
  - 'name'
  - 'year'
  - 'selling_price'
  - 'km_driven'
  - 'fuel'
  - 'seller_type'
  - 'transmission'
  - 'owner'
  - 'mileage'
  - 'engine'
  - 'max_power'
  - 'torque'
  - 'seats'

keep_makes:
 - 'Audi'
 - 'BMW'
 - 'Chevrolet'
 - 'Fiat'
 - 'Ford'
 - 'Honda'
 - 'Hyundai'
 - 'Isuzu'
 - 'Jaguar'
 - 'Jeep'
 - 'Kia'
 - 'Land'
 - 'Lexus'
 - 'Mercedes-Benz'
 - 'Mitsubishi'
 - 'Nissan'
 - 'Toyota'
 - 'Volkswagen'
 - 'Volvo'
